name: Validate uWrap

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate uWrap
        run: node ci/validate_wrap.mjs examples/WRAP_001
